# common:
#   msg_source: 1                                         #0: not use Lidar
#                                                         #1: packet message comes from online Lidar
#                                                         #2: packet message comes from ROS or ROS2
#                                                         #3: packet message comes from Pcap file
#                                                         #4: packet message comes from Protobuf-UDP
#                                                         #5: point cloud comes from Protobuf-UDP
#   send_packet_ros: false                                #true: Send packets through ROS or ROS2(Used to record packet)
#   send_point_cloud_ros: true                            #true: Send point cloud through ROS or ROS2
#   send_packet_proto: false                              #true: Send packets through Protobuf-UDP
#   send_point_cloud_proto: false                         #true: Send point cloud through Protobuf-UDP
#   pcap_path: /home/robosense/lidar.pcap                 #The path of pcap file

# lidar:
#   - driver:
#       lidar_type: RS128            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
#       frame_id: /rslidar           #Frame id of message
#       msop_port: 6699              #Msop port of lidar
#       difop_port: 7788             #Difop port of lidar
#       start_angle: 0               #Start angle of point cloud
#       end_angle: 360               #End angle of point cloud 
#       min_distance: 0.2            #Minimum distance of point cloud
#       max_distance: 200            #Maximum distance of point cloud
#       use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
#                                    #False-- Use the system clock as the timestamp  
#     ros:
#       ros_recv_packet_topic: /rslidar_packets          #Topic used to receive lidar packets from ROS
#       ros_send_packet_topic: /rslidar_packets          #Topic used to send lidar packets through ROS
#       ros_send_point_cloud_topic: /rslidar_points      #Topic used to send point cloud through ROS
#     proto:
#       point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
#       point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
#       msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
#       msop_send_port: 60022                            #Port number which the msop packets will be send to 
#       difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
#       difop_send_port: 60023                           #Port number which the difop packets will be send to 
#       point_cloud_send_ip: 127.0.0.1                   #Ip address which the point cloud will be send to 
#       packet_send_ip: 127.0.0.1                        #Ip address which the lidar packets will be send to
common:
  msg_source: 1                                         
  send_packet_ros: true                               
  send_point_cloud_ros: true                           
  send_packet_proto: false                              
  send_point_cloud_proto: false                         
  pcap_path: /home/robosense/lidar.pcap 
lidar:
  - driver:
      lidar_type: RS16         
      frame_id: /middle/rslidar           
      msop_port: 6688          
      difop_port: 7799          
      start_angle: 0              
      end_angle: 360               
      min_distance: 0.2            
      max_distance: 200            
      use_lidar_clock: false        
    ros:
      ros_recv_packet_topic: /middle/rslidar_packets    
      ros_send_packet_topic: /middle/rslidar_packets    
      ros_send_point_cloud_topic: /middle/points_raw     
    proto:
      point_cloud_recv_port: 60021                     
      point_cloud_send_port: 60021                     
      msop_recv_port: 60022                       
      msop_send_port: 60022                       
      difop_recv_port: 60023                      
      difop_send_port: 60023       
      point_cloud_send_ip: 192.168.20.202               
      packet_send_ip: 192.168.20.202
  - driver:
      lidar_type: RS16          
      frame_id: /left/rslidar           
      msop_port: 6677             
      difop_port: 8899        
      start_angle: 0              
      end_angle: 360               
      min_distance: 0.2            
      max_distance: 200            
      use_lidar_clock: false        
    ros:
      ros_recv_packet_topic: /left/rslidar_packets    
      ros_send_packet_topic: /left/rslidar_packets    
      ros_send_point_cloud_topic: /left/points_raw  
    proto:
      point_cloud_recv_port: 60024                     
      point_cloud_send_port: 60024                     
      msop_recv_port: 60025                       
      msop_send_port: 60025                       
      difop_recv_port: 60026                      
      difop_send_port: 60026       
      point_cloud_send_ip: 192.168.20.200                  
      packet_send_ip: 192.168.20.200
  - driver:
      lidar_type: RS16           
      frame_id: /right/rslidar           
      msop_port: 6699        
      difop_port: 7788            
      start_angle: 0              
      end_angle: 360               
      min_distance: 0.2            
      max_distance: 200            
      use_lidar_clock: false        
    ros:
      ros_recv_packet_topic: /right/rslidar_packets    
      ros_send_packet_topic: /right/rslidar_packets    
      ros_send_point_cloud_topic: /right/points_raw
    proto:
      point_cloud_recv_port: 60027                     
      point_cloud_send_port: 60027                     
      msop_recv_port: 60028                       
      msop_send_port: 60028                       
      difop_recv_port: 60029                      
      difop_send_port: 60029       
      point_cloud_send_ip: 192.168.20.201                   
      packet_send_ip: 192.168.20.201

# 192.168.20.200 201 202[TODO] forgot ~/robosense/ .sh tools/lidar config [Get][Set] 
