// Generated by gencpp from file common_msgs/PolarBoundary.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_POLARBOUNDARY_H
#define COMMON_MSGS_MESSAGE_POLARBOUNDARY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct PolarBoundary_
{
  typedef PolarBoundary_<ContainerAllocator> Type;

  PolarBoundary_()
    : header()
    , distance()  {
    }
  PolarBoundary_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::common_msgs::PolarBoundary_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::PolarBoundary_<ContainerAllocator> const> ConstPtr;

}; // struct PolarBoundary_

typedef ::common_msgs::PolarBoundary_<std::allocator<void> > PolarBoundary;

typedef boost::shared_ptr< ::common_msgs::PolarBoundary > PolarBoundaryPtr;
typedef boost::shared_ptr< ::common_msgs::PolarBoundary const> PolarBoundaryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::PolarBoundary_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::PolarBoundary_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::PolarBoundary_<ContainerAllocator1> & lhs, const ::common_msgs::PolarBoundary_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::PolarBoundary_<ContainerAllocator1> & lhs, const ::common_msgs::PolarBoundary_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_msgs::PolarBoundary_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::PolarBoundary_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::PolarBoundary_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::PolarBoundary_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::PolarBoundary_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::PolarBoundary_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::PolarBoundary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e9525e625ae2426ab1a6408e28e8c8a";
  }

  static const char* value(const ::common_msgs::PolarBoundary_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e9525e625ae2426ULL;
  static const uint64_t static_value2 = 0xab1a6408e28e8c8aULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::PolarBoundary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/PolarBoundary";
  }

  static const char* value(const ::common_msgs::PolarBoundary_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::PolarBoundary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32[] distance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common_msgs::PolarBoundary_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::PolarBoundary_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolarBoundary_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::PolarBoundary_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::PolarBoundary_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance[]" << std::endl;
    for (size_t i = 0; i < v.distance.size(); ++i)
    {
      s << indent << "  distance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_POLARBOUNDARY_H
