// Generated by gencpp from file common_msgs/V2V.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_V2V_H
#define COMMON_MSGS_MESSAGE_V2V_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <common_msgs/PlatoonState.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct V2V_
{
  typedef V2V_<ContainerAllocator> Type;

  V2V_()
    : header()
    , platoon_info()  {
    }
  V2V_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , platoon_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::common_msgs::PlatoonState_<ContainerAllocator>  _platoon_info_type;
  _platoon_info_type platoon_info;





  typedef boost::shared_ptr< ::common_msgs::V2V_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::V2V_<ContainerAllocator> const> ConstPtr;

}; // struct V2V_

typedef ::common_msgs::V2V_<std::allocator<void> > V2V;

typedef boost::shared_ptr< ::common_msgs::V2V > V2VPtr;
typedef boost::shared_ptr< ::common_msgs::V2V const> V2VConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::V2V_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::V2V_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::V2V_<ContainerAllocator1> & lhs, const ::common_msgs::V2V_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.platoon_info == rhs.platoon_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::V2V_<ContainerAllocator1> & lhs, const ::common_msgs::V2V_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_msgs::V2V_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::V2V_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::V2V_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::V2V_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::V2V_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::V2V_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::V2V_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84dd78ba72f6eb4041f0491a6158eda6";
  }

  static const char* value(const ::common_msgs::V2V_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84dd78ba72f6eb40ULL;
  static const uint64_t static_value2 = 0x41f0491a6158eda6ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::V2V_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/V2V";
  }

  static const char* value(const ::common_msgs::V2V_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::V2V_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"common_msgs/PlatoonState platoon_info\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: common_msgs/PlatoonState\n"
"std_msgs/Header header\n"
"\n"
"# member vehicle state\n"
"common_msgs/VehicleState[] vehicles\n"
"================================================================================\n"
"MSG: common_msgs/VehicleState\n"
"# Id of the vehicle\n"
"std_msgs/Header header \n"
"\n"
"# Basic info of the vehicle\n"
"\n"
"# Odometry info of the vehicle\n"
"nav_msgs/Odometry odom\n"
"\n"
"# Dynamic state of vehicle\n"
"common_msgs/VehicleDynamicState dynamics\n"
"\n"
"# Chassis state of vehicle\n"
"common_msgs/ChassisState chassis\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: common_msgs/VehicleDynamicState\n"
"std_msgs/Header  header\n"
"\n"
"float32 lon_speed\n"
"float32 lon_accel\n"
"float32 lat_speed\n"
"float32 lat_accel\n"
"float32 yaw_rate\n"
"float32 yaw_accel\n"
"================================================================================\n"
"MSG: common_msgs/ChassisState\n"
"std_msgs/Header header\n"
"\n"
"# real acc throttle value\n"
"float32 throttle\n"
"\n"
"# real brake pressure\n"
"float32 brake\n"
"\n"
"# vehicle run mode\n"
"uint8 run_mode\n"
"\n"
"# Level of accelaration, unit in m/s^2, throttle is positive, braking is negative\n"
"float32 accel\n"
"\n"
"# Level of steering on front wheel, unit in radian, left turning is positive\n"
"float32 steer\n"
"\n"
"# Gear\n"
"int8 gear\n"
"\n"
"# Parking\n"
"bool parking_brake\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::common_msgs::V2V_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::V2V_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.platoon_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct V2V_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::V2V_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::V2V_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "platoon_info: ";
    s << std::endl;
    Printer< ::common_msgs::PlatoonState_<ContainerAllocator> >::stream(s, indent + "  ", v.platoon_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_V2V_H
