// Generated by gencpp from file can_msgs/Frames.msg
// DO NOT EDIT!


#ifndef CAN_MSGS_MESSAGE_FRAMES_H
#define CAN_MSGS_MESSAGE_FRAMES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <can_msgs/Frame.h>

namespace can_msgs
{
template <class ContainerAllocator>
struct Frames_
{
  typedef Frames_<ContainerAllocator> Type;

  Frames_()
    : header()
    , frames()  {
    }
  Frames_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frames(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::can_msgs::Frame_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::can_msgs::Frame_<ContainerAllocator> >> _frames_type;
  _frames_type frames;





  typedef boost::shared_ptr< ::can_msgs::Frames_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_msgs::Frames_<ContainerAllocator> const> ConstPtr;

}; // struct Frames_

typedef ::can_msgs::Frames_<std::allocator<void> > Frames;

typedef boost::shared_ptr< ::can_msgs::Frames > FramesPtr;
typedef boost::shared_ptr< ::can_msgs::Frames const> FramesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_msgs::Frames_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_msgs::Frames_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::can_msgs::Frames_<ContainerAllocator1> & lhs, const ::can_msgs::Frames_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.frames == rhs.frames;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::can_msgs::Frames_<ContainerAllocator1> & lhs, const ::can_msgs::Frames_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace can_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Frames_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_msgs::Frames_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Frames_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_msgs::Frames_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Frames_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_msgs::Frames_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_msgs::Frames_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a652a31438717760a5dd3f589c696e07";
  }

  static const char* value(const ::can_msgs::Frames_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa652a31438717760ULL;
  static const uint64_t static_value2 = 0xa5dd3f589c696e07ULL;
};

template<class ContainerAllocator>
struct DataType< ::can_msgs::Frames_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_msgs/Frames";
  }

  static const char* value(const ::can_msgs::Frames_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_msgs::Frames_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Frame[] frames\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: can_msgs/Frame\n"
"Header header\n"
"uint32 id\n"
"bool is_rtr\n"
"bool is_extended\n"
"bool is_error\n"
"uint8 dlc\n"
"uint8[8] data\n"
;
  }

  static const char* value(const ::can_msgs::Frames_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_msgs::Frames_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Frames_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_msgs::Frames_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_msgs::Frames_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frames[]" << std::endl;
    for (size_t i = 0; i < v.frames.size(); ++i)
    {
      s << indent << "  frames[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::can_msgs::Frame_<ContainerAllocator> >::stream(s, indent + "    ", v.frames[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_MSGS_MESSAGE_FRAMES_H
