(cl:defpackage common_msgs-msg
  (:use )
  (:export
   "<CHASSISSTATE>"
   "CHASSISSTATE"
   "<CONTROLCOMMAND>"
   "CONTROLCOMMAND"
   "<GPSINFO>"
   "GPSINFO"
   "<PLATOONSTATE>"
   "PLATOONSTATE"
   "<POLARBOUNDARY>"
   "POLARBOUNDARY"
   "<STOPDECISION>"
   "STOPDECISION"
   "<V2V>"
   "V2V"
   "<VEHICLEDYNAMICSTATE>"
   "VEHICLEDYNAMICSTATE"
   "<VEHICLESTATE>"
   "VEHICLESTATE"
  ))

