#pragma once 
#include "protocol.h" 
class ADCU_PowerCmd:public protocol{
  public:
    ADCU_PowerCmd();
    virtual ~ADCU_PowerCmd()=default;
    virtual void Update(uint8_t *data) override;
    void Reset() override;
    double ADCU_AD12VMCPwrdownCnfm_Cmd();
    void SetADCU_AD12VMCPwrdownCnfm_Cmd(double ADCU_AD12VMCPwrdownCnfm_Cmd);
    void Set_p_ADCU_AD12VMCPwrdownCnfm_Cmd(double ADCU_AD12VMCPwrdownCnfm_Cmd);
    double ADCU_AD12VMCPwrup_Cmd();
    void SetADCU_AD12VMCPwrup_Cmd(double ADCU_AD12VMCPwrup_Cmd);
    void Set_p_ADCU_AD12VMCPwrup_Cmd(double ADCU_AD12VMCPwrup_Cmd);
    double ADCU_AD12VRCPwrdownCnfm_Cmd();
    void SetADCU_AD12VRCPwrdownCnfm_Cmd(double ADCU_AD12VRCPwrdownCnfm_Cmd);
    void Set_p_ADCU_AD12VRCPwrdownCnfm_Cmd(double ADCU_AD12VRCPwrdownCnfm_Cmd);
    double ADCU_AD12VRCPwrup_Cmd();
    void SetADCU_AD12VRCPwrup_Cmd(double ADCU_AD12VRCPwrup_Cmd);
    void Set_p_ADCU_AD12VRCPwrup_Cmd(double ADCU_AD12VRCPwrup_Cmd);
    double ADCU_AD12VSC1Pwrup_Cmd();
    void SetADCU_AD12VSC1Pwrup_Cmd(double ADCU_AD12VSC1Pwrup_Cmd);
    void Set_p_ADCU_AD12VSC1Pwrup_Cmd(double ADCU_AD12VSC1Pwrup_Cmd);
    double ADCU_AD12VSC2Pwrup_Cmd();
    void SetADCU_AD12VSC2Pwrup_Cmd(double ADCU_AD12VSC2Pwrup_Cmd);
    void Set_p_ADCU_AD12VSC2Pwrup_Cmd(double ADCU_AD12VSC2Pwrup_Cmd);
    double ADCU_AD12VSC3Pwrup_Cmd();
    void SetADCU_AD12VSC3Pwrup_Cmd(double ADCU_AD12VSC3Pwrup_Cmd);
    void Set_p_ADCU_AD12VSC3Pwrup_Cmd(double ADCU_AD12VSC3Pwrup_Cmd);
    double ADCU_AD12VSC4Pwrup_Cmd();
    void SetADCU_AD12VSC4Pwrup_Cmd(double ADCU_AD12VSC4Pwrup_Cmd);
    void Set_p_ADCU_AD12VSC4Pwrup_Cmd(double ADCU_AD12VSC4Pwrup_Cmd);
    double ADCU_AD12VSC5Pwrup_Cmd();
    void SetADCU_AD12VSC5Pwrup_Cmd(double ADCU_AD12VSC5Pwrup_Cmd);
    void Set_p_ADCU_AD12VSC5Pwrup_Cmd(double ADCU_AD12VSC5Pwrup_Cmd);
    double ADCU_AD12VSC6Pwrup_Cmd();
    void SetADCU_AD12VSC6Pwrup_Cmd(double ADCU_AD12VSC6Pwrup_Cmd);
    void Set_p_ADCU_AD12VSC6Pwrup_Cmd(double ADCU_AD12VSC6Pwrup_Cmd);
    double ADCU_AD24VMCPwrdownCnfm_Cmd();
    void SetADCU_AD24VMCPwrdownCnfm_Cmd(double ADCU_AD24VMCPwrdownCnfm_Cmd);
    void Set_p_ADCU_AD24VMCPwrdownCnfm_Cmd(double ADCU_AD24VMCPwrdownCnfm_Cmd);
    double ADCU_AD24VMCPwrup_Cmd();
    void SetADCU_AD24VMCPwrup_Cmd(double ADCU_AD24VMCPwrup_Cmd);
    void Set_p_ADCU_AD24VMCPwrup_Cmd(double ADCU_AD24VMCPwrup_Cmd);
    double ADCU_ADChasPwrup_Cmd();
    void SetADCU_ADChasPwrup_Cmd(double ADCU_ADChasPwrup_Cmd);
    void Set_p_ADCU_ADChasPwrup_Cmd(double ADCU_ADChasPwrup_Cmd);
    double ADCU_ADPA12VPwrdownCnfm_Cmd();
    void SetADCU_ADPA12VPwrdownCnfm_Cmd(double ADCU_ADPA12VPwrdownCnfm_Cmd);
    void Set_p_ADCU_ADPA12VPwrdownCnfm_Cmd(double ADCU_ADPA12VPwrdownCnfm_Cmd);
    double ADCU_ADPA12VPwrup_Cmd();
    void SetADCU_ADPA12VPwrup_Cmd(double ADCU_ADPA12VPwrup_Cmd);
    void Set_p_ADCU_ADPA12VPwrup_Cmd(double ADCU_ADPA12VPwrup_Cmd);
    double ADCU_ADPA24VPwrdownCnfm_Cmd();
    void SetADCU_ADPA24VPwrdownCnfm_Cmd(double ADCU_ADPA24VPwrdownCnfm_Cmd);
    void Set_p_ADCU_ADPA24VPwrdownCnfm_Cmd(double ADCU_ADPA24VPwrdownCnfm_Cmd);
    double ADCU_ADPA24VPwrup_Cmd();
    void SetADCU_ADPA24VPwrup_Cmd(double ADCU_ADPA24VPwrup_Cmd);
    void Set_p_ADCU_ADPA24VPwrup_Cmd(double ADCU_ADPA24VPwrup_Cmd);
    double ADCU_ADVehPwrup_Cmd();
    void SetADCU_ADVehPwrup_Cmd(double ADCU_ADVehPwrup_Cmd);
    void Set_p_ADCU_ADVehPwrup_Cmd(double ADCU_ADVehPwrup_Cmd);
    double ADCU_PwrCmd_Checksum();
    void SetADCU_PwrCmd_Checksum(double ADCU_PwrCmd_Checksum);
    void Set_p_ADCU_PwrCmd_Checksum(double ADCU_PwrCmd_Checksum);
    double ADCU_PwrCmd_RollCnt();
    void SetADCU_PwrCmd_RollCnt(double ADCU_PwrCmd_RollCnt);
    void Set_p_ADCU_PwrCmd_RollCnt(double ADCU_PwrCmd_RollCnt);
  private:
    double ADCU_AD12VMCPwrdownCnfm_Cmd_;
    double ADCU_AD12VMCPwrup_Cmd_;
    double ADCU_AD12VRCPwrdownCnfm_Cmd_;
    double ADCU_AD12VRCPwrup_Cmd_;
    double ADCU_AD12VSC1Pwrup_Cmd_;
    double ADCU_AD12VSC2Pwrup_Cmd_;
    double ADCU_AD12VSC3Pwrup_Cmd_;
    double ADCU_AD12VSC4Pwrup_Cmd_;
    double ADCU_AD12VSC5Pwrup_Cmd_;
    double ADCU_AD12VSC6Pwrup_Cmd_;
    double ADCU_AD24VMCPwrdownCnfm_Cmd_;
    double ADCU_AD24VMCPwrup_Cmd_;
    double ADCU_ADChasPwrup_Cmd_;
    double ADCU_ADPA12VPwrdownCnfm_Cmd_;
    double ADCU_ADPA12VPwrup_Cmd_;
    double ADCU_ADPA24VPwrdownCnfm_Cmd_;
    double ADCU_ADPA24VPwrup_Cmd_;
    double ADCU_ADVehPwrup_Cmd_;
    double ADCU_PwrCmd_Checksum_;
    double ADCU_PwrCmd_RollCnt_;
};
