#pragma once
#include "protocol.h" 
class CDCU_VehState:public protocol{
  public:
    CDCU_VehState();
    virtual ~CDCU_VehState()=default;
    void Reset() override;
    virtual void Update(uint8_t *data) override;
    double CDCU_BCM_ErrLevel();
    void UpdateCDCU_BCM_ErrLevel();
    double CDCU_BMS_ErrLevel();
    void UpdateCDCU_BMS_ErrLevel();
    double CDCU_Bat_LowSOC();
    void UpdateCDCU_Bat_LowSOC();
    double CDCU_CANBusOff_St();
    void UpdateCDCU_CANBusOff_St();
    double CDCU_EHB_ErrLevel();
    void UpdateCDCU_EHB_ErrLevel();
    double CDCU_EPB_ErrLevel();
    void UpdateCDCU_EPB_ErrLevel();
    double CDCU_EPS_ErrLevel();
    void UpdateCDCU_EPS_ErrLevel();
    double CDCU_FtCrash_St();
    void UpdateCDCU_FtCrash_St();
    double CDCU_LvBat_LowVolt();
    void UpdateCDCU_LvBat_LowVolt();
    double CDCU_MCU_ErrLevel();
    void UpdateCDCU_MCU_ErrLevel();
    double CDCU_PDU_ErrLevel();
    void UpdateCDCU_PDU_ErrLevel();
    double CDCU_RrCrash_St();
    void UpdateCDCU_RrCrash_St();
    double CDCU_TirePresrAlarm_St();
    void UpdateCDCU_TirePresrAlarm_St();
    double CDCU_VehEmgcySwh_St();
    void UpdateCDCU_VehEmgcySwh_St();
    double CDCU_VehSt_Checksum();
    void UpdateCDCU_VehSt_Checksum();
    double CDCU_VehSt_RollCnt();
    void UpdateCDCU_VehSt_RollCnt();
    double CDCU_Veh_ErrCode();
    void UpdateCDCU_Veh_ErrCode();
    double CDCU_Veh_ErrLevel();
    void UpdateCDCU_Veh_ErrLevel();
    double CDCU_Veh_RunMode();
    void UpdateCDCU_Veh_RunMode();
    double VCU_TestSig_U8();
    void UpdateVCU_TestSig_U8();
  private:
    double CDCU_BCM_ErrLevel_;
    double CDCU_BMS_ErrLevel_;
    double CDCU_Bat_LowSOC_;
    double CDCU_CANBusOff_St_;
    double CDCU_EHB_ErrLevel_;
    double CDCU_EPB_ErrLevel_;
    double CDCU_EPS_ErrLevel_;
    double CDCU_FtCrash_St_;
    double CDCU_LvBat_LowVolt_;
    double CDCU_MCU_ErrLevel_;
    double CDCU_PDU_ErrLevel_;
    double CDCU_RrCrash_St_;
    double CDCU_TirePresrAlarm_St_;
    double CDCU_VehEmgcySwh_St_;
    double CDCU_VehSt_Checksum_;
    double CDCU_VehSt_RollCnt_;
    double CDCU_Veh_ErrCode_;
    double CDCU_Veh_ErrLevel_;
    double CDCU_Veh_RunMode_;
    double VCU_TestSig_U8_;
};
